### PR TITLE
Simplify config instantiation

### PR DESCRIPTION
**Pull request by surajpaib**
## Description

This PR simplifies the instantiation of a configuration by refactoring the existing code and making it more user-friendly. Monai bundle scripts are avoided and configuration parsers are used to separate from monai's structure and error-handling
## Related Issue

N/A

## Type of Change

- [x] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/lighter/lighter/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/lighter/lighter/blob/master/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [x] I've written tests for all new methods and classes that I created.
- [x] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by ibro45** [comment]
Awesome, thank you! Can we just not use `assert`? 

Btw, from PL 2.0, Trainer has not `.tune()` method, and instead you'd have to use the Tuner class. We'll have to modify the code for that but that can be a separate PR.

**Comment by surajpaib** [comment]
> Awesome, thank you! Can we just not use assert, and instead raise errors?

Assert would also raise an error, right? Do we want to have specific error codes?

**Comment by ibro45** [comment]
Just style concerns, i think asserts are usually for debugging and testing purposes

**Comment by surajpaib** [comment]
Got it, will make the edit!

**Comment by ibro45** [comment]
Thanks! Btw how do the error messages look like now, is it better or do we still have to figure that out?

**Comment by surajpaib** [comment]
> Thanks! Btw how do the error messages look like now, is it better or do we still have to figure that out?

This fixes it. The error messages were thrown because we not only instantiated our config, but also called it through monai   config. 

Now these two are de-coupled

**Review by ibro45 — APPROVED** [review]

**Pull request merged**
