### PR TITLE
Create viewer classes for interactive use in iPython notebooks

### PR DESCRIPTION
**Pull request by kbressem**
I find it exceptionally useful and convenient to view images in interactive sessions directly inside the jupyter notebook. So I've written viewer classes that allow to view 2d or 3d arrays in a similar manner like a radiologist would. 

## BasicViewer
The base class of all viewers. Can show a single image, optionally with mask overlay or label. Also allows to add a title to the image. 

image

_please note, this image does **not** show pneumonia ;)_

## ListViewer
As subclass of BasicViewer that allows to view multiple images at once. Useful to compare images or to be implemented in other functions. In [trainlib](https://github.com/kbressem/trainlib) I use it in `DataLoader.show_batch`, to inspect the batch before it is passed to the model. 

image

## DicomExplorer 
This viewer class provides more useful information about the distribution of intensity values. Could be useful to check if images were normalized correctly. 

image

This PR also adds extensive tests for all viewers. Ideally it is not merged before #9

### CODE REVIEW

**Comment by surajpaib** [comment]
@kbressem This looks very useful indeed. Thanks for sharing. 

@ibro45 I think this should go into the `contrib`  folder with all the other tools we have. I'll setup a repo for it tomorrow and make it a submodule for this repo

**Comment by ibro45** [comment]
@kbressem Really nice stuff! 
@surajpaib Agree; it might even be its own package (what do you think @kbressem?), but contrib would do for the moment

**Comment by surajpaib** [comment]
I think it should be it's own package for sure. We can even skip the submodule and have it as an independent package completely. Any medical imaging/ use case specific tools will go there.

**Comment by kbressem** [comment]
We could start using it here and then iteratively refine. When it proofs to be reliable, I can create a stand alone package. I'll move it to contrib

**Comment by ibro45** [comment]
https://github.com/project-lighter/contrib
Want to PR it there?

**Comment by kbressem** [comment]
> https://github.com/project-lighter/contrib Want to PR it there?

Yes, will do

**Pull request closed without merging**
