### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by surajpaib**
Add logo and update README

### CODE REVIEW

**Comment by ibro45** [comment]
Wait are we going with that color scheme? Also can we have the fire orange in the dark mode logo too?

**Comment by surajpaib** [comment]
> Wait are we going with that color scheme? Also can we have the fire orange in the dark mode logo too?

This doesn't look as nice, let me also add it so you can see

**Comment by surajpaib** [comment]
We can change the color scheme, just wanted to have this to start

**Comment by ibro45** [comment]
https://github.com/project-lighter/lighter/blob/add_logo/assets/images/lighter_light.png
https://github.com/project-lighter/lighter/blob/add_logo/assets/images/lighter_dark_v2.png

I think these should work pretty well, but with a different color scheme. Orange + charcoal, or maybe some kind of blue or teal instead of charcoal, we could try some more combos next time we see each other

**Comment by ibro45** [comment]
how do you like it? @surajpaib

**Pull request merged**
