### PR TITLE
Memfix

### PR DESCRIPTION
**Pull request by surajpaib**
Addresses #82 

https://github.com/Lightning-AI/pytorch-lightning/issues/15656

does not seem to fix the memory leak - memory usage keeps increasing. 

Adding the garbage collector keeps the memory usage constant throughout the prediction loop. 

For good measure, I have also added code to clear the `_predictions` in the `predict_loop` of the trainer that causes accumulation during the batch. I figure the gc already clears this but added it nonetheless

### CODE REVIEW

**Comment by ibro45** [comment]
can we write it as 
```python
def _clear_cached_preds(trainer):  # Just a suggestion, feel free to change the name
    """Describe"""
    if trainer.state.stage == "predict":
        trainer.predict_loop._predictions = [[] for _ in range(trainer.predict_loop.num_dataloaders)]
        gc.collect()
```

Also, should we place it `system.on_predict_batch_start()` https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#on-predict-batch-start?
Two benefits:
- In case any callback is trying to access `trainer.predict_loop._predictions` on the batch end, this way it's available until the start of the next batch.
- Nice to remove it from the `_base_step()` logic, it's quite abrupt

**Comment by surajpaib** [comment]
@ibro45 We can call it either on batch start or end, does not make a difference. I am quite certain nothing accesses `_predictions` unless its on an epoch level

**Comment by surajpaib** [comment]
Do we want this by default in `LightningModule` like now?
Or do we want to move it to the writer? 

I am thinking of moving it to the writer because this is unexplained behaviour should someone try to use their own writer and try to save predictions at the end of the epoch

**Comment by surajpaib** [comment]
https://github.com/project-lighter/lighter/blob/ca9794e247c886554a88bfcafcf4b910b7037f73/lighter/callbacks/writer/base.py#L108

Would be placed here instead

**Comment by ibro45** [comment]
Good point let's do that

**Comment by ibro45** [comment]
Lgtm

**Pull request merged**
