### PR TITLE
Pass config to logger + simplify project import 

### PR DESCRIPTION
**Pull request by surajpaib**
## Description

Addresses issue #20 

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/lighter/lighter/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/lighter/lighter/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by ibro45** [comment]
Thanks a lot! I actually thinks this looks way better than we imagined it!

**Comment by surajpaib** [comment]
@ibro45 Thanks! 

A few things to discuss though before we make it ready for merge.

Do we want to enforce a particular location for the config with the `trainer.default_root_dir`? Right now it uses the current working directory but I can see a case when someone uses a file called `config.yaml` in the cwd to train. 

Maybe making it a temporary file is a better solution here?

**Comment by ibro45** [comment]
What about https://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python for the purpose of passing the config to other modules?

For actual config dumping, that should be done in the logger, in the output dir specified there.

What do you think?

**Comment by surajpaib** [comment]
> For actual config dumping, that should be done in the logger, in the output dir specified there.
We need to dump it before we access it right?

I wanted to do the `tempfile` way but I'm uncertain about how we can close it effectively. Let me do some reading

**Comment by surajpaib** [comment]
Now that I think of it, I guess we could just delete it once we load the config. For the dumping do you mean to "officially" dump so that the user can access it?

**Comment by ibro45** [comment]
> For the dumping do you mean to "officially" dump so that the user can access it

Yes, sorry, my wording was weird.

---

Here's a different idea:

Add a `add_config()` method to logger callbacks (`LighterLogger`) which will just store the config into `self.config`. In the `setup()` method just use `self.config` to upload it to wandb and to dump it into the `log_dir`.

The `setup()` method is called only after a trainer's `fit`/`test`/etc. method is called, and the wandb/tensorboard init happens in `setup()`.

So, in `cli.py`, instead of
```python
parser.export_config_file(parser.get(), f"{trainer.default_root_dir}/config.yaml")
```
Do this:
```python
for callback in trainer.callbacks:
    if hasattr("add_config"):
        callback.add_config(parser.get())
```

This way, we also allow any other callback to access the config for any purpose it may need it.

**Comment by surajpaib** [comment]
I like this approach, instead of looking for a method, maybe we can simplify it as,

```{python}
for callback in trainer.callbacks:
    if hasattr("config"):
        callback.config = parser.get()
```

So any callback that needs a `config` will get it.

**Comment by ibro45** [comment]
Nice! I see you changed cli.py to runner.py, you checked out https://github.com/project-lighter/lighter/blob/a96e653fe770098c1763ab821b4662c0d1184d3e/lighter/runner.py right? For the "interactive" mode, to just load a trainer and/or a system directly in a script or notebook.

**Comment by surajpaib** [comment]
Yep, exactly, almost the same content, just cleaner now thanks to monai

**Comment by ibro45** [comment]
Were you planning on having separate trainer and system instantiations when you only want to load one of them?

**Comment by surajpaib** [comment]
I was planning to just use the parser to get trainer and system objects. 

Basically instantiate the parser with yaml file and then get whatever objects I want to get out of it

**Comment by surajpaib** [comment]
@ibro45 Nope, lets merge it!

**Comment by surajpaib** [comment]
Should I merge this?

**Pull request merged**
