### PR TITLE
Fix MONAI-ITK orientation. Improve Writer docstrings.

### PR DESCRIPTION
**Pull request by ibro45**
## Description

Removed my temp fix for https://github.com/Project-MONAI/MONAI/issues/6985 as it has been fixed.

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/lighter/lighter/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/lighter/lighter/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by surajpaib** [comment]
@ibro45 We should also fix the monai version in poetry. Otherwise this fix doesn't work right?

**Comment by surajpaib** [comment]
Right now, we have this,
https://github.com/project-lighter/lighter/blob/009e7da49c6ad9dacfd5aa1e795ca2913d0c7f23/pyproject.toml#L54

It will pull the latest one if available, but it's not necessary that it picks up the version with this fix.

**Comment by ibro45** [comment]
Cool will do it thanks

**Review by surajpaib — APPROVED** [review]
LGTM

**Comment by ibro45** [comment]
Thanks Suraj!

**Pull request merged**
