### PR TITLE
Improve console logging and tracebacks

### PR DESCRIPTION
**Pull request by ibro45**
## Description

- [Rich](https://github.com/Textualize/rich) added to our loguru
- Loguru captures all loggers from other libraries
- Loguru captures warnings made through `warnings` standard library
- Tracebacks improved through Rich, both by looking neater, and by suppressing (not printing the code, only the location) of select modules. Those modules include `fire`, `monai.bundle`, PL's `Trainer`, etc. This should be updated as we notice unnecessary module.

This is what it currently looks like when you try to specify a non-existing class in the config.

image

## Related Issue

[
](https://github.com/project-lighter/lighter/issues/100)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/lighter/lighter/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/lighter/lighter/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by surajpaib** [comment]
Thanks for doing this! I think it looks great overall. 

Something more for discussion here - should we suppress all INFO messages by default and provide it only when a verbose flag is set? I feel like on repeated runs, it does not provide any useful information

If Jessica has the time, we should also get her feedback on this logging bit.

**Comment by ibro45** [comment]
> should we suppress all INFO messages by default and provide it only when a verbose flag is set?
I'm leaning towards keeping them, as it seems too radical not to, but will need to think about it. Feels like it could bring more confusion than benefit?

> If Jessica has the time, we should also get her feedback on this logging bit.
Probably once we merged a version with master

One thing that I'm not happy with is when `warnings` warnings are called in PyTorch Lightning from a function in their `rank_zero` module instead of on the spot, so you cannot go directly to the file where it happened to examine it.

image
For PL, we can check if it's coming from `rank_zero` module and then just increase the depth in `logger.opt(depth=2).warning` from 2 to 3 to get the module before it.

**Comment by ibro45** [comment]
Should i move the module to utils/ ?

**Comment by ibro45** [comment]
I would merge this as-is right now. Still beneficial to have it on master, even though it should be improved down the road.

To improve:
- Error messages can be very long. Ideally, we would like to shorten them for the same modules whose tracebacks we suppress. https://github.com/Textualize/rich/issues/3271

- Patching `warnings.showwarning` cannot take into account the `stacklevel` argument from `warnings.warn()`. This is apparent in warnings from PL being shown as coming from the `rank_zero` module, instead of a level or few before, as they indicate through `stacklevel`. https://github.com/Delgan/loguru/issues/1076#issuecomment-1928620985

- Errors coming from DataLoader are off (as if logging isn't set up). I described it here, but I am still unsure how to fix it. https://github.com/Textualize/rich/issues/3269

- I will create an issue for us to keep track of modules that we think should be suppressed https://github.com/project-lighter/lighter/blob/a63195f35411627a531eac3172ac629da39ca74d/lighter/logging.py#L2

**Comment by surajpaib** [comment]
@ibro45 Mind if I take a look at the Dataloader logging functionality?

A lot of errors are usually spawned from this and it would be nice to have a more informed logging here.

**Comment by ibro45** [comment]
> @ibro45 Mind if I take a look at the Dataloader logging functionality?
> 
> A lot of errors are usually spawned from this and it would be nice to have a more informed logging here.

Oh please do! We can merge it after then

**Comment by surajpaib** [comment]
Lets merge this for now? More improvements pending fix of https://github.com/Project-MONAI/MONAI/issues/7451

**Pull request merged**
